services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - db
      - redis
    networks:
      - laravel
    environment:
      - PHP_MEMORY_LIMIT=512M
      - REDIS_HOST=redis
      - DB_HOST=db            # <-- pastikan Laravel .env ikut ni
      - DB_PORT=3306
      - DB_USERNAME=root
      - DB_PASSWORD=yoprint

  nginx:
    image: nginx:latest
    container_name: laravel-nginx
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel

  redis:
    image: redis:alpine
    container_name: laravel-redis
    ports:
      - "6379:6379"
    networks:
      - laravel

  db:
    image: mysql:8.0
    container_name: laravel-mysql
    restart: unless-stopped
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=yoprint
      - MYSQL_DATABASE=laravel
    networks:
      - laravel

volumes:
  mysql_data:

networks:
  laravel:
    driver: bridge
